### PR TITLE
SolarApp adjustments

### PR DESCRIPTION
**Pull request by cwhanse**
- Rename CommentTag to Tag, CommentTags to Tags
- add Mixed value for moduleOrientationItemType

### CODE REVIEW

**Comment by jrippingale** [comment]
Actually, I have one question, I don't see that Site.Tags[] or Task.Tags[] where the array was added to the existing objects.  Would that be in this one or would the renaming automatically create that effect?

**Comment by cwhanse** [comment]
We didn't add Comments to those objects before, unless we've got a configuration management issue.

**Comment by jrippingale** [comment]
ok - I am mixing threads I think.  Did we add Tags[] to Comment.Tags[]?


[image: Blu Banyan] <https://www.blubanyan.com/>

[image: O-NetSuite Solution Partner]
Jan Rippingale
CEO
Blu Banyan <https://blubanyan.com/>

m:  <707.234.5395>707.234.5395
e: ***@***.***

**Comment by jrippingale** [comment]
Yes, The Comment.Tags[] is exactly right now.  Thank you!  Sheldon, I think are good to go! :-)

**Comment by cwhanse** [comment]
@shelcrow I'll resubmit to the development branch

**Comment by shelcrow** [comment]
@cwhanse This is fine, I will merge soon

**Pull request merged**
