### PR TITLE
WIP: Remake ProdCertification - not ready for review or merge

### PR DESCRIPTION
**Pull request by cwhanse**
Adds:

CertificationDate
CertificationExpirationDate
The data for CertificationDate and CertificationExpirationDate were being encoded in the StartTime and EndTime metadata for ProdCertificationValue.

Replaces

ProdCertificationName with CertificationName
ProdCertificationValue with CertificateValue
ProdCertificationType with CertificationTypeProduct

Replaces #44

### CODE REVIEW

**Comment by shelcrow** [comment]
Can you submit this to the new repo? Thank you

**Comment by jrippingale** [comment]
I love this change!  Not sure how to do the pull request into the new
open-orange-button repository, but we need it to be there....


[image: Blu Banyan] <https://www.blubanyan.com/>

[image: O-NetSuite Solution Partner]
Jan Rippingale
CEO
Blu Banyan <https://blubanyan.com/>

m:  <707.234.5395>707.234.5395
e: ***@***.***

**Comment by cwhanse** [comment]
@shelcrow  no because the new repo hasn't been updated after merging the other 3 PRs. I assumed you were waiting to update until after #44 was resolved here.

**Comment by shelcrow** [comment]
@cwhanse The taxonomy in the new repository is now updated to reflect your latest PRs, I think it is good now to open a PR against.

**Pull request closed without merging**
