### PR TITLE
add Warranty, Warranties

### PR DESCRIPTION
**Pull request by cwhanse**

### CODE REVIEW

**Comment by jrippingale** [comment]
The Warranty and Warranties object look correct to me.  I think we are missing Product.Warranties[]

**Comment by cwhanse** [comment]
Should Product.WarrantyMaterial go away?

**Comment by jrippingale** [comment]
Yes, WarrantyMaterial should go away as it is covered by Warranty.WarrantyType (Power, Material, Service)

**Comment by cwhanse** [comment]
The new element WarrantyType has item type warrantyType but with no enumerated units, what should those be?

**Comment by jrippingale** [comment]
Power
Service
Material
Other

I think we'd be covered then.  How did we lose these values?  Maybe the Load In... overwrote them?

**Comment by cwhanse** [comment]
> Maybe the Load In... overwrote them?

@shelcrow I don't think the Load In brought over the new item type used by one of the loaded elements.

**Review by jrippingale — APPROVED** [review]
Looks good reviewed earlier.

**Pull request merged**
